<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Grpc.Net.Client" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\services\Knowledge\NexConvo.Knowledge.Infrastructure\NexConvo.Knowledge.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\src\services\Knowledge\NexConvo.Knowledge.Application\NexConvo.Knowledge.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\services\Knowledge\NexConvo.Knowledge.Api\NexConvo.Knowledge.Api.csproj" />
  </ItemGroup>

</Project>
