<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../NexConvo.Identity.Infrastructure/NexConvo.Identity.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
  </ItemGroup>
</Project>
