// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexConvo.Chat.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexConvo.Chat.Infrastructure.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexConvo.Chat.Domain.Entities.ChannelConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_access_token");

                    b.Property<string>("EncryptedAppSecret")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_app_secret");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_account_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastTestError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_test_error");

                    b.Property<int?>("LastTestLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("last_test_latency_ms");

                    b.Property<int>("LastTestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_test_status");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_tested_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerifyToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verify_token");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_channel_connections_tenant_id");

                    b.HasIndex("TenantId", "Channel", "ExternalAccountId")
                        .IsUnique()
                        .HasDatabaseName("idx_channel_connections_unique_active")
                        .HasFilter("is_active = true");

                    b.ToTable("channel_connections", (string)null);
                });

            modelBuilder.Entity("NexConvo.Chat.Domain.Entities.ChatAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_chat_audit_logs_occurred_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_chat_audit_logs_tenant_id");

                    b.ToTable("chat_audit_logs", (string)null);
                });

            modelBuilder.Entity("NexConvo.Chat.Domain.Entities.WorkspaceChatSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("DataRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("data_retention_days");

                    b.Property<string>("FallbackProviders")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("fallback_providers");

                    b.Property<double>("HandoffConfidenceThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.65000000000000002)
                        .HasColumnName("handoff_confidence_threshold");

                    b.Property<int>("MaxUnansweredMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_unanswered_messages");

                    b.Property<int>("PiiMaskingLevel")
                        .HasColumnType("integer")
                        .HasColumnName("pii_masking_level");

                    b.Property<string>("PrimaryModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("primary_model");

                    b.Property<int>("PrimaryProvider")
                        .HasColumnType("integer")
                        .HasColumnName("primary_provider");

                    b.Property<bool>("SentimentEscalationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("sentiment_escalation_enabled");

                    b.Property<int>("SentimentSensitivity")
                        .HasColumnType("integer")
                        .HasColumnName("sentiment_sensitivity");

                    b.Property<string>("SystemPromptOverride")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("system_prompt_override");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerPhrases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("trigger_phrases");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("idx_workspace_chat_settings_tenant_id");

                    b.ToTable("workspace_chat_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
